// Package hopper is a job queue and message broker for Go, built on the
// database the application already runs. PostgreSQL is the first engine.
//
// A Client inserts jobs, claims them in batches, runs them on registered
// workers and finalizes results in batches. Any number of clients run against
// one database; work is claimed with FOR UPDATE SKIP LOCKED, so adding
// replicas adds throughput.
//
//	workers := hopper.NewWorkers()
//	hopper.AddWorker(workers, &SendEmailWorker{})
//
//	client, err := hopper.NewClient(hopperpgx.New(pool), &hopper.Config{
//		Queues:  map[string]hopper.QueueConfig{hopper.QueueDefault: {MaxWorkers: 100}},
//		Workers: workers,
//	})
//	g.Go(func() error { return client.Run(ctx) })
//
//	_, err = client.InsertTx(ctx, tx, SendEmail{UserID: 42}, nil) // commits with tx
//
// Jobs run at least once. A job runs twice only when the process running it
// is lost mid-job, so workers must be idempotent.
//
// The database schema is installed with the hoppermigrate package.
package hopper

import "github.com/parallelworks/hopper/driver"

// JobID identifies a job. It is a UUIDv7 generated by the database.
type JobID = driver.JobID

// ParseJobID parses the canonical 8-4-4-4-12 text form of a JobID.
func ParseJobID(s string) (JobID, error) { return driver.ParseJobID(s) }

// JobState is a job's position in the state machine.
type JobState = driver.JobState

// Job states. Available, scheduled and retryable all mean "claim once
// scheduled_at has passed"; they are distinct only so operators can see why a
// job is waiting.
const (
	JobStatePending   = driver.JobStatePending
	JobStateAvailable = driver.JobStateAvailable
	JobStateScheduled = driver.JobStateScheduled
	JobStateRunning   = driver.JobStateRunning
	JobStateRetryable = driver.JobStateRetryable
	JobStateCompleted = driver.JobStateCompleted
	JobStateCancelled = driver.JobStateCancelled
	JobStateDiscarded = driver.JobStateDiscarded
)

// JobRow is a job as stored, with its encoded args. Workers receive a typed
// Job[T] that embeds it.
type JobRow = driver.JobRow

// AttemptError records one failed attempt of a job.
type AttemptError = driver.AttemptError

// ErrNotFound is returned when a job does not exist, live or in history.
var ErrNotFound = driver.ErrNotFound
