package driver

import (
	"database/sql/driver"
	"encoding/hex"
	"fmt"
)

// JobID identifies a job. It is a UUIDv7 generated by the database, so it is
// time-ordered, safe to expose outside the application and does not reveal
// volume. The zero value is not a valid ID.
type JobID [16]byte

// ParseJobID parses the canonical 8-4-4-4-12 text form.
func ParseJobID(s string) (JobID, error) {
	var id JobID
	if len(s) != 36 || s[8] != '-' || s[13] != '-' || s[18] != '-' || s[23] != '-' {
		return id, fmt.Errorf("hopper: invalid job ID %q", s)
	}
	var buf [32]byte
	copy(buf[0:8], s[0:8])
	copy(buf[8:12], s[9:13])
	copy(buf[12:16], s[14:18])
	copy(buf[16:20], s[19:23])
	copy(buf[20:32], s[24:36])
	if _, err := hex.Decode(id[:], buf[:]); err != nil {
		return JobID{}, fmt.Errorf("hopper: invalid job ID %q", s)
	}
	return id, nil
}

// IsZero reports whether the ID is unset.
func (id JobID) IsZero() bool { return id == JobID{} }

// String returns the canonical 8-4-4-4-12 text form.
func (id JobID) String() string {
	var buf [36]byte
	hex.Encode(buf[0:8], id[0:4])
	buf[8] = '-'
	hex.Encode(buf[9:13], id[4:6])
	buf[13] = '-'
	hex.Encode(buf[14:18], id[6:8])
	buf[18] = '-'
	hex.Encode(buf[19:23], id[8:10])
	buf[23] = '-'
	hex.Encode(buf[24:36], id[10:16])
	return string(buf[:])
}

// MarshalText implements encoding.TextMarshaler, which also gives JSON
// encoding as a string.
func (id JobID) MarshalText() ([]byte, error) { return []byte(id.String()), nil }

// UnmarshalText implements encoding.TextUnmarshaler.
func (id *JobID) UnmarshalText(text []byte) error {
	parsed, err := ParseJobID(string(text))
	if err != nil {
		return err
	}
	*id = parsed
	return nil
}

// Scan implements sql.Scanner. It accepts the text form or 16 raw bytes.
func (id *JobID) Scan(src any) error {
	switch v := src.(type) {
	case nil:
		*id = JobID{}
		return nil
	case string:
		return id.UnmarshalText([]byte(v))
	case []byte:
		if len(v) == 16 {
			copy(id[:], v)
			return nil
		}
		return id.UnmarshalText(v)
	case [16]byte:
		*id = v
		return nil
	default:
		return fmt.Errorf("hopper: cannot scan %T into JobID", src)
	}
}

// Value implements driver.Valuer.
func (id JobID) Value() (driver.Value, error) { return id.String(), nil }
